import type { TrendingProject } from '../types';

/**
 * Export projects to CSV format
 */
export function exportToCSV(projects: TrendingProject[], filename: string = 'trending-projects'): void {
  const headers = ['Rank', 'Name', 'Owner', 'Description', 'Language', 'Total Stars', 'Growth', 'Link'];
  
  const rows = projects.map(p => {
    const parts = p.name.split('/');
    const repo = parts[1] || p.name;
    const owner = parts[0] || '';
    return [
      p.rank,
      repo,
      owner,
      `"${(p.description || '').replace(/"/g, '""')}"`,
      p.keywords[0] || 'Unknown',
      p.totalStars,
      p.growth,
      p.link,
    ].join(',');
  });
  
  const csv = [headers.join(','), ...rows].join('\n');
  downloadFile(csv, `${filename}.csv`, 'text/csv;charset=utf-8');
}

/**
 * Export projects to Markdown format
 */
export function exportToMarkdown(projects: TrendingProject[], filename: string = 'trending-projects'): void {
  const lines: string[] = [
    '# GitHub Trending Projects',
    '',
    `> Exported on ${new Date().toLocaleDateString()}`,
    '',
    '## Projects',
    '',
    '| Rank | Project | Language | Stars | Growth | Description |',
    '|------|---------|----------|-------|--------|-------------|',
  ];
  
  projects.forEach(p => {
    const [, repo] = p.name.split('/');
    const description = (p.description || '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
    lines.push(
      `| ${p.rank} | [${repo || p.name}](${p.link}) | ${p.keywords[0] || 'Unknown'} | ${p.totalStars} | ${p.growth} | ${description} |`
    );
  });
  
  lines.push('');
  lines.push('---');
  lines.push('*Generated by Trending Dashboard*');
  
  const md = lines.join('\n');
  downloadFile(md, `${filename}.md`, 'text/markdown;charset=utf-8');
}

function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
